import { sql } from "drizzle-orm";
import { check, numeric, pgTable, text, timestamp, uniqueIndex, uuid } from "drizzle-orm/pg-core";
import { jornadas } from "./jornadas.js";

export const resultados = pgTable(
    "resultados",
    {
        id: uuid("id").primaryKey().default(sql`uuidv7()`),
        jornadaId: uuid("jornada_id")
            .notNull()
            .references(() => jornadas.id, { onDelete: "cascade" }),
        resultado1: text("resultado_1").notNull(),
        resultado2: text("resultado_2").notNull(),
        resultado3: text("resultado_3").notNull(),
        resultado4: text("resultado_4").notNull(),
        resultado5: text("resultado_5").notNull(),
        resultado6: text("resultado_6").notNull(),
        resultado7: text("resultado_7").notNull(),
        resultado8: text("resultado_8").notNull(),
        resultado9: text("resultado_9").notNull(),
        resultado10: text("resultado_10").notNull(),
        resultado11: text("resultado_11").notNull(),
        resultado12: text("resultado_12").notNull(),
        resultado13: text("resultado_13").notNull(),
        resultado14: text("resultado_14").notNull(),
        resultado15: text("resultado_15").notNull(),
        premioCat10: numeric("premio_cat_10", { precision: 12, scale: 2, mode: "number" }).notNull().default(0),
        premioCat11: numeric("premio_cat_11", { precision: 12, scale: 2, mode: "number" }).notNull().default(0),
        premioCat12: numeric("premio_cat_12", { precision: 12, scale: 2, mode: "number" }).notNull().default(0),
        premioCat13: numeric("premio_cat_13", { precision: 12, scale: 2, mode: "number" }).notNull().default(0),
        premioCat14: numeric("premio_cat_14", { precision: 12, scale: 2, mode: "number" }).notNull().default(0),
        premioCat15: numeric("premio_cat_15", { precision: 12, scale: 2, mode: "number" }).notNull().default(0),
        createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
        updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    },
    (t) => [
        uniqueIndex("resultados_jornada_key").on(t.jornadaId),
        check("resultados_resultado_1_check", sql`${t.resultado1} ~ '^[1X2]$'`),
        check("resultados_resultado_2_check", sql`${t.resultado2} ~ '^[1X2]$'`),
        check("resultados_resultado_3_check", sql`${t.resultado3} ~ '^[1X2]$'`),
        check("resultados_resultado_4_check", sql`${t.resultado4} ~ '^[1X2]$'`),
        check("resultados_resultado_5_check", sql`${t.resultado5} ~ '^[1X2]$'`),
        check("resultados_resultado_6_check", sql`${t.resultado6} ~ '^[1X2]$'`),
        check("resultados_resultado_7_check", sql`${t.resultado7} ~ '^[1X2]$'`),
        check("resultados_resultado_8_check", sql`${t.resultado8} ~ '^[1X2]$'`),
        check("resultados_resultado_9_check", sql`${t.resultado9} ~ '^[1X2]$'`),
        check("resultados_resultado_10_check", sql`${t.resultado10} ~ '^[1X2]$'`),
        check("resultados_resultado_11_check", sql`${t.resultado11} ~ '^[1X2]$'`),
        check("resultados_resultado_12_check", sql`${t.resultado12} ~ '^[1X2]$'`),
        check("resultados_resultado_13_check", sql`${t.resultado13} ~ '^[1X2]$'`),
        check("resultados_resultado_14_check", sql`${t.resultado14} ~ '^[1X2]$'`),
        check("resultados_resultado_15_check", sql`${t.resultado15} ~ '^[012M]-[012M]$'`),
        check("resultados_premio_10_check", sql`${t.premioCat10} >= 0`),
        check("resultados_premio_11_check", sql`${t.premioCat11} >= 0`),
        check("resultados_premio_12_check", sql`${t.premioCat12} >= 0`),
        check("resultados_premio_13_check", sql`${t.premioCat13} >= 0`),
        check("resultados_premio_14_check", sql`${t.premioCat14} >= 0`),
        check("resultados_premio_15_check", sql`${t.premioCat15} >= 0`),
    ],
);