CREATE TABLE "resultados" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"jornada_id" uuid NOT NULL,
	"resultado_1" text NOT NULL,
	"resultado_2" text NOT NULL,
	"resultado_3" text NOT NULL,
	"resultado_4" text NOT NULL,
	"resultado_5" text NOT NULL,
	"resultado_6" text NOT NULL,
	"resultado_7" text NOT NULL,
	"resultado_8" text NOT NULL,
	"resultado_9" text NOT NULL,
	"resultado_10" text NOT NULL,
	"resultado_11" text NOT NULL,
	"resultado_12" text NOT NULL,
	"resultado_13" text NOT NULL,
	"resultado_14" text NOT NULL,
	"resultado_15" text NOT NULL,
	"premio_cat_10" numeric(12, 2) DEFAULT 0 NOT NULL,
	"premio_cat_11" numeric(12, 2) DEFAULT 0 NOT NULL,
	"premio_cat_12" numeric(12, 2) DEFAULT 0 NOT NULL,
	"premio_cat_13" numeric(12, 2) DEFAULT 0 NOT NULL,
	"premio_cat_14" numeric(12, 2) DEFAULT 0 NOT NULL,
	"premio_cat_15" numeric(12, 2) DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "resultados_resultado_1_check" CHECK ("resultados"."resultado_1" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_2_check" CHECK ("resultados"."resultado_2" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_3_check" CHECK ("resultados"."resultado_3" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_4_check" CHECK ("resultados"."resultado_4" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_5_check" CHECK ("resultados"."resultado_5" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_6_check" CHECK ("resultados"."resultado_6" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_7_check" CHECK ("resultados"."resultado_7" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_8_check" CHECK ("resultados"."resultado_8" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_9_check" CHECK ("resultados"."resultado_9" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_10_check" CHECK ("resultados"."resultado_10" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_11_check" CHECK ("resultados"."resultado_11" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_12_check" CHECK ("resultados"."resultado_12" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_13_check" CHECK ("resultados"."resultado_13" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_14_check" CHECK ("resultados"."resultado_14" ~ '^[1X2]$'),
	CONSTRAINT "resultados_resultado_15_check" CHECK ("resultados"."resultado_15" ~ '^[012M]-[012M]$'),
	CONSTRAINT "resultados_premio_10_check" CHECK ("resultados"."premio_cat_10" >= 0),
	CONSTRAINT "resultados_premio_11_check" CHECK ("resultados"."premio_cat_11" >= 0),
	CONSTRAINT "resultados_premio_12_check" CHECK ("resultados"."premio_cat_12" >= 0),
	CONSTRAINT "resultados_premio_13_check" CHECK ("resultados"."premio_cat_13" >= 0),
	CONSTRAINT "resultados_premio_14_check" CHECK ("resultados"."premio_cat_14" >= 0),
	CONSTRAINT "resultados_premio_15_check" CHECK ("resultados"."premio_cat_15" >= 0)
);
--> statement-breakpoint
ALTER TABLE "resultados" ADD CONSTRAINT "resultados_jornada_id_jornadas_id_fk" FOREIGN KEY ("jornada_id") REFERENCES "public"."jornadas"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "resultados_jornada_key" ON "resultados" USING btree ("jornada_id");